name: Start_Issues_WkFw
on: issues

jobs:
    issues_job:
        runs-on: ubuntu-latest
        steps:
            - name: "Triggers Jobs When Issue "
              uses: actions/checkout@v3

            - name: "Printing Message"
              run: echo "The Actions is ${{ toJSON(github.event)}} "

    send_email_job:
        runs-on: ubuntu-latest
        steps:
           - name: Send Email
             uses: hilarion5/send-mail@v1
             with:
               smtp-server: smtp.gmail.com
               smtp-port: 465
               smtp-secure: true
               from-email: janardhanasunkara9@gmail.com
               to-email: janardhanasunkara9@gmail.com
               username: janardhanasunkara9
               password: Anthrixmodel9!
               subject: Test Email
               body: This is a test email sent from GitHub Actions.
               html: |
                      <h1>This is a test email</h1>
                      <p>Test Paragraph</p>
