name: Start_Issues_WkFw
on: issues

jobs:
    issues_job:
        runs-on: ubuntu-latest
        steps:
            - name: "Triggers Jobs When Issue "
              uses: actions/checkout@v3

            - name: "Printing Message"
              run: echo "The Actions is ${{ toJSON(github.event)}} "
