name: "2_python_wkflw"
on: workflow_dispatch

jobs:
  python_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Code from Repo and run it on Runner Machine"
        uses: actions/checkout@v3

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: "Run Python Program"
        run: echo "python 1_python.py"
